-- 浏览 h/t/n/s 
map("n", "t", "j", { noremap = false })
map("n", "n", "k", { noremap = false })
map("n", "s", "l", { noremap = false })
map("n", "j", "t", { noremap = false })
map("n", "k", "n", { noremap = false })
map("n", "l", "s", { noremap = false })
map("n", "T", "J", { noremap = false })
map("n", "N", "K", { noremap = false })
map("n", "S", "L", { noremap = false })
map("n", "J", "T", { noremap = false })
map("n", "K", "N", { noremap = false })
map("n", "L", "S", { noremap = false })

-- 命令行下 h/t/n/s 
map("v", "t", "j", { noremap = false })
map("v", "n", "k", { noremap = false })
map("v", "s", "l", { noremap = false })
map("v", "j", "t", { noremap = false })
map("v", "k", "n", { noremap = false })
map("v", "l", "s", { noremap = false })
map("v", "T", "J", { noremap = false })
map("v", "N", "K", { noremap = false })
map("v", "S", "L", { noremap = false })
map("v", "J", "T", { noremap = false })
map("v", "K", "N", { noremap = false })
map("v", "L", "S", { noremap = false })

-- 跳跃 
map("n", "(", "^", { noremap = false })
map("n", ")", "$", { noremap = false })
map("n", "^", "(", { noremap = false })
map("n", "$", ")", { noremap = false })
