#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# 焦点
# yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             first_child

# 阴影 
yabai -m config window_topmost               off
yabai -m config window_shadow                float

# 透明
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95

# 边框
# yabai -m config window_border                off
# yabai -m config window_border_width          3
# yabai -m config active_window_border_color   0xff81a1c1
# yabai -m config normal_window_border_color   0x007A808C
# yabai -m config insert_feedback_color        0xff81a1c1

yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.50
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8


# 应用状态
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^DaisyDisk$" manage=off
yabai -m rule --add app="^ExpressVPN$" manage=off
yabai -m rule --add app="^Motrix$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Alacritty$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^哔哩哔哩$" manage=off

# Mac亦可设定
# yabai -m rule --add app="WeChat" space=1
# yabai -m rule --add app="Firefox" space=2
# yabai -m rule --add app="kitty" space=3
# yabai -m rule --add app="Mail" space=6
# yabai -m rule --add app="Spotify" space=7

# show on all spaces
# yabai -m rule --add app="^Alacritty$" sticky=on
# yabai -m rule --add app="^Stickies$" sticky=on
# yabai -m rule --add app="^Numi$" sticky=on
# yabai -m rule --add app="^Notion$" sticky=on

# all display top
# yabai -m config external_bar all:32:0

echo "yabai configuration loaded.."
