#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# LIGHTBLUE=0xff7da6ff
# BLUE=0xff7aa2f7
# EVENLIGHTERBLUE=0xff0db9d7
# ORANGE=0xffff9e64
# RED=0xfff7768e
# YELLOW=0xffe0af68
# PURPLE=0xffad8ee6
# GREEN=0xff9ece6a
# BG=0xda11121D
# FG=0xaaa9b1d6
# BG=0xda11121D

# yabai -m config active_window_border_color   0xffad8ee6
# yabai -m config normal_window_border_color   0xaaa9b1d6
# yabai -m config insert_feedback_color        0xffad8ee6

# global settings
yabai -m config focus_follows_mouse          autoraise
# yabai -m config focus_follows_mouse          off
yabai -m config mouse_follows_focus          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
# yabai -m config window_shadow                off
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config window_border                off
yabai -m config window_border_width          5
# yabai -m config active_window_border_color   0xff7aa2f7
# yabai -m config normal_window_border_color   0xff444b6a
# yabai -m config active_window_border_color   0xff81A1C1
# yabai -m config normal_window_border_color   0xff7A808C
# yabai -m config insert_feedback_color        0xff61afef
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^DaisyDisk$" manage=off
yabai -m rule --add app="^ExpressVPN$" manage=off
yabai -m rule --add app="^Motrix$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Alacritty$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off

# Mac亦可设定
# yabai -m rule --add app="WeChat" space=1
# yabai -m rule --add app="Safari" space=2
# yabai -m rule --add app="iTerm" space=3
# yabai -m rule --add app="Mail" space=6
# yabai -m rule --add app="Spotify" space=7
# yabai -m rule --add app="Music" space=7

# show on all spaces
# yabai -m rule --add app="^kitty$" sticky=on
# yabai -m rule --add app="^Min$" sticky=on
# yabai -m rule --add app="^Stickies$" sticky=on
# yabai -m rule --add app="^Numi$" sticky=on
# yabai -m rule --add app="^Notion$" sticky=on

# all display top
# yabai -m config external_bar all:32:0

echo "yabai configuration loaded.."
